require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb
    - spec/support/matchers/have_attr_accessor.rb
    - lib/tasks/cucumber.rake
    - features/support/_circleci_formatter.rb
    - spec/support/extensions/its.rb

Layout/IndentArray:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

RSpec/ExpectActual:
  Exclude:
    - spec/routing/application_routing_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/**/*.rake_spec.rb
    - spec/routing/**/*_spec.rb
    - spec/support/shared_examples/coerced_attr_accessor.rb

RSpec/FilePath:
  Exclude:
    - spec/config/application_spec.rb
    - spec/config/initializers/maintenance_spec.rb

RSpec/InstanceVariable:
  Exclude:
    - spec/lib/schedule_generator_test_case_spec.rb
    - spec/helpers/google_services_helper_spec.rb
    - spec/middlewares/maintenance_spec.rb

RSpec/NestedGroups:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
