require: rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb
    - spec/support/matchers/have_attr_accessor.rb
    - lib/tasks/cucumber.rake
    - features/support/_circleci_formatter.rb
  RunRailsCops: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/step_definitions/**/*

Style/AsciiIdentifiers:
  Exclude:
    - features/step_definitions/**/*

RSpec/DescribeClass:
  Exclude:
    - spec/**/*.rake_spec.rb
    - spec/routing/**/*_spec.rb
    - spec/support/shared_examples/coerced_attr_accessor.rb

RSpec/InstanceVariable:
  Exclude:
    - spec/lib/schedule_generator_test_case_spec.rb
    - spec/helpers/google_analytics_helper_spec.rb
