AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb
    - spec/support/matchers/have_attr_accessor.rb
    - lib/tasks/cucumber.rake
    - features/support/_circleci_formatter.rb
  RunRailsCops: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/step_definitions/**/*

Style/AsciiIdentifiers:
  Exclude:
    - features/step_definitions/**/*
